package com.antispam.blocker.domain.scoring

import android.content.Context
import android.util.Log
import org.json.JSONObject
import java.io.BufferedReader
import java.io.File
import java.io.FileReader
import java.io.InputStreamReader

/**
 * Phase 3: data-driven `def_code → P(BLOCK)` lookup, generated by
 * `scripts/build_assets_from_dataset.py` (writes assets/def_code_risk.json).
 *
 * Сглажено с prior=overall_block_rate (α=20) — стабильно и для кодов с малым
 * числом семплов. На устройстве это даёт «третью грань» risk-сигнала помимо
 * 6-digit prefix histogram и legacy prefixRisk.
 */
class DefCodeRiskTable private constructor(
    private val defCodes: Map<String, Float>,
    val fallbackRisk: Float,
    val version: String?,
) {

    /** Возвращает риск 0..1 по нормализованному номеру (+7XXX…). */
    fun riskFor(normalized: String?): Float {
        if (normalized == null) return fallbackRisk
        if (!normalized.startsWith("+7")) return fallbackRisk
        val digits = normalized.filter { it.isDigit() }
        if (digits.length < 4) return fallbackRisk
        val def = digits.substring(1, 4)
        return defCodes[def] ?: fallbackRisk
    }

    companion object {
        private const val TAG = "DefCodeRiskTable"
        private const val ASSET_PATH = "def_code_risk.json"
        private const val DEFAULT_FALLBACK = 0.5f

        @Volatile private var INSTANCE: DefCodeRiskTable? = null

        fun get(context: Context): DefCodeRiskTable {
            INSTANCE?.let { return it }
            synchronized(this) {
                INSTANCE?.let { return it }
                val loaded = load(context.applicationContext)
                INSTANCE = loaded
                return loaded
            }
        }

        fun invalidate() {
            synchronized(this) { INSTANCE = null }
        }

        private fun load(context: Context): DefCodeRiskTable {
            val fromFile = runCatching {
                val file = File(context.filesDir, ASSET_PATH)
                if (file.exists() && file.length() > 0) {
                    FileReader(file).use { it.readText() }
                } else null
            }.getOrNull()

            val json = fromFile ?: runCatching {
                context.assets.open(ASSET_PATH).use { stream ->
                    BufferedReader(InputStreamReader(stream)).readText()
                }
            }.getOrNull()

            if (json.isNullOrBlank()) {
                Log.w(TAG, "asset $ASSET_PATH unavailable; using fallback=$DEFAULT_FALLBACK")
                return DefCodeRiskTable(emptyMap(), DEFAULT_FALLBACK, null)
            }

            return try {
                val obj = JSONObject(json)
                val version = obj.optString("version", null)
                val fallback = obj.optDouble("fallback_risk", DEFAULT_FALLBACK.toDouble()).toFloat()
                val defObj = obj.optJSONObject("def_codes")
                val map = HashMap<String, Float>(defObj?.length() ?: 0)
                if (defObj != null) {
                    val it = defObj.keys()
                    while (it.hasNext()) {
                        val k = it.next()
                        map[k] = defObj.getDouble(k).toFloat()
                    }
                }
                val sourceTag = if (fromFile != null) "filesDir" else "assets"
                Log.i(TAG, "loaded ${map.size} def_codes from $ASSET_PATH ($sourceTag, version=$version, fb=$fallback)")
                DefCodeRiskTable(map, fallback, version)
            } catch (t: Throwable) {
                Log.w(TAG, "$ASSET_PATH parse failed", t)
                DefCodeRiskTable(emptyMap(), DEFAULT_FALLBACK, null)
            }
        }
    }
}
