package com.antispam.blocker.domain.scoring

import android.content.Context
import android.util.Log
import org.json.JSONObject
import java.io.BufferedReader
import java.io.File
import java.io.FileReader
import java.io.InputStreamReader

/**
 * Phase 3: data-driven `def_code → operator_bucket` lookup, generated by
 * `scripts/build_assets_from_dataset.py` (writes assets/operator_bucket.json).
 *
 * Buckets: mts | megafon | beeline | tele2 | mvno | other.
 * Используется в [FeatureExtractor] для вычисления 5-D one-hot operator bucket.
 *
 * Если ассета нет / def_code не найден — все 5 фичей равны 0 (one-hot = "other").
 */
class OperatorBucketTable private constructor(
    private val defCodes: Map<String, String>,
    val version: String?,
) {

    /** Возвращает bucket по +7XXX… → 3-digit DEF code → bucket. */
    fun bucketFor(normalized: String?): String {
        if (normalized == null) return BUCKET_OTHER
        if (!normalized.startsWith("+7")) return BUCKET_OTHER
        val digits = normalized.filter { it.isDigit() }
        if (digits.length < 4) return BUCKET_OTHER
        val def = digits.substring(1, 4)
        return defCodes[def] ?: BUCKET_OTHER
    }

    companion object {
        const val BUCKET_MTS = "mts"
        const val BUCKET_MEGAFON = "megafon"
        const val BUCKET_BEELINE = "beeline"
        const val BUCKET_TELE2 = "tele2"
        const val BUCKET_MVNO = "mvno"
        const val BUCKET_OTHER = "other"

        private const val TAG = "OperatorBucketTable"
        private const val ASSET_PATH = "operator_bucket.json"

        @Volatile private var INSTANCE: OperatorBucketTable? = null

        fun get(context: Context): OperatorBucketTable {
            INSTANCE?.let { return it }
            synchronized(this) {
                INSTANCE?.let { return it }
                val loaded = load(context.applicationContext)
                INSTANCE = loaded
                return loaded
            }
        }

        fun invalidate() {
            synchronized(this) { INSTANCE = null }
        }

        private fun load(context: Context): OperatorBucketTable {
            val fromFile = runCatching {
                val file = File(context.filesDir, ASSET_PATH)
                if (file.exists() && file.length() > 0) {
                    FileReader(file).use { it.readText() }
                } else null
            }.getOrNull()

            val json = fromFile ?: runCatching {
                context.assets.open(ASSET_PATH).use { stream ->
                    BufferedReader(InputStreamReader(stream)).readText()
                }
            }.getOrNull()

            if (json.isNullOrBlank()) {
                Log.w(TAG, "asset $ASSET_PATH unavailable, all buckets → other")
                return OperatorBucketTable(emptyMap(), null)
            }

            return try {
                val obj = JSONObject(json)
                val version = obj.optString("version", null)
                val defObj = obj.optJSONObject("def_codes")
                val map = HashMap<String, String>(defObj?.length() ?: 0)
                if (defObj != null) {
                    val it = defObj.keys()
                    while (it.hasNext()) {
                        val k = it.next()
                        map[k] = defObj.optString(k, BUCKET_OTHER)
                    }
                }
                val sourceTag = if (fromFile != null) "filesDir" else "assets"
                Log.i(TAG, "loaded ${map.size} def_codes from $ASSET_PATH ($sourceTag, version=$version)")
                OperatorBucketTable(map, version)
            } catch (t: Throwable) {
                Log.w(TAG, "$ASSET_PATH parse failed", t)
                OperatorBucketTable(emptyMap(), null)
            }
        }
    }
}
