package com.antispam.blocker.domain.scoring

import android.content.Context
import android.util.Log
import org.json.JSONObject
import java.io.BufferedReader
import java.io.File
import java.io.FileReader
import java.io.InputStreamReader

/**
 * Data-driven prefix → risk lookup, loaded from `app/src/main/assets/prefix_risk.json`.
 *
 * The JSON is generated by `scripts/build_assets_from_dataset.py` from the same
 * training dataset that powers the TFLite model. Loading the same table on
 * device guarantees that `prefixRisk` at runtime matches what the model saw
 * during training.
 *
 * Falls back to the legacy heuristic if the asset is missing or malformed.
 */
class PrefixRiskTable private constructor(
    private val prefixes: Map<String, Float>,
    private val prefixLength: Int,
    val fallbackRisk: Float,
    val version: String?,
) {

    fun riskFor(normalized: String?): Float {
        if (normalized == null || normalized.isEmpty()) return 0f
        if (prefixes.isEmpty()) return legacyHeuristic(normalized)
        val key = normalized.take(prefixLength)
        prefixes[key]?.let { return it }
        // shorter-prefix fallback
        for (k in intArrayOf(5, 4)) {
            prefixes[normalized.take(k)]?.let { return it }
        }
        if (normalized.startsWith("+84")) return 0.8f
        return fallbackRisk
    }

    companion object {
        private const val TAG = "PrefixRiskTable"
        private const val ASSET_PATH = "prefix_risk.json"

        @Volatile private var INSTANCE: PrefixRiskTable? = null

        fun get(context: Context): PrefixRiskTable {
            INSTANCE?.let { return it }
            synchronized(this) {
                INSTANCE?.let { return it }
                val loaded = load(context.applicationContext)
                INSTANCE = loaded
                return loaded
            }
        }

        /** Сбросить кеш — например после успешного скачивания обновления. */
        fun invalidate() {
            synchronized(this) { INSTANCE = null }
        }

        private fun load(context: Context): PrefixRiskTable {
            // Сначала пробуем filesDir (туда RemoteUpdateWorker кладёт скачанные обновления).
            val fromFile = runCatching {
                val file = File(context.filesDir, ASSET_PATH)
                if (file.exists() && file.length() > 0) {
                    FileReader(file).use { it.readText() }
                } else null
            }.getOrNull()

            val json = fromFile ?: runCatching {
                context.assets.open(ASSET_PATH).use { stream ->
                    BufferedReader(InputStreamReader(stream)).readText()
                }
            }.getOrNull()

            if (json.isNullOrBlank()) {
                Log.w(TAG, "asset $ASSET_PATH unavailable, falling back to legacy heuristic")
                return PrefixRiskTable(emptyMap(), 6, 0.1f, null)
            }

            return try {
                val obj = JSONObject(json)
                val prefixLength = obj.optInt("prefix_length", 6)
                val fallback = obj.optDouble("fallback_risk", 0.1).toFloat()
                val version = obj.optString("version", null)
                val prefixesObj = obj.optJSONObject("prefixes")
                val map = HashMap<String, Float>(prefixesObj?.length() ?: 0)
                if (prefixesObj != null) {
                    val it = prefixesObj.keys()
                    while (it.hasNext()) {
                        val k = it.next()
                        map[k] = prefixesObj.getDouble(k).toFloat()
                    }
                }
                val sourceTag = if (fromFile != null) "filesDir" else "assets"
                Log.i(TAG, "loaded ${map.size} prefixes from $ASSET_PATH ($sourceTag, version=$version)")
                PrefixRiskTable(map, prefixLength, fallback, version)
            } catch (t: Throwable) {
                Log.w(TAG, "$ASSET_PATH parse failed, falling back to legacy heuristic", t)
                PrefixRiskTable(emptyMap(), 6, 0.1f, null)
            }
        }

        /** Legacy heuristic kept verbatim for the no-asset fallback path. */
        internal fun legacyHeuristic(normalized: String): Float = when {
            normalized.startsWith("+84") -> 0.8f
            normalized.startsWith("+7800") -> 0.25f
            normalized.startsWith("+7495") -> 0.4f
            normalized.startsWith("+7499") -> 0.4f
            normalized.startsWith("+7844") -> 0.3f
            normalized.startsWith("+7900") -> 0.65f
            normalized.startsWith("+7958") -> 0.65f
            normalized.startsWith("+7966") -> 0.65f
            normalized.startsWith("+7969") -> 0.65f
            else -> 0.1f
        }
    }
}
